//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt_texteditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeTable
    {
        public int task_id { get; set; }
        public int line_no { get; set; }
        public string user_id { get; set; }
        public string text { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TaskTable TaskTable { get; set; }
    }
}
